
services:
  streamlit:
    build: .
    container_name: streamlit_app
    ports:
      - "15031:15031"
    depends_on:
      - mysql
    volumes:
      - .:/app
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=1234
      - MYSQL_DATABASE=minwon
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]
    runtime: nvidia  # ✨ 요거 중요!

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: minwon
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
