[theme]

base = "light"
font = "nanum gothic"
codeFont = "nanum gothic"
headingFont = "nanum gothic"
codeFontSize = "16px"
primaryColor = "#2766C2"


[server]
runOnSave = true

[client]
showSidebarNavigation = false

