[app]
ai = "on" #ai on/off 기능
rag = "on" #ragai on/off 기능
lab = "off" #실험실 기능 on/off
admin_password = "1234" #관리자 비밀번호
default_grade = 0
default_model = "민원팩토리 모델"
department = ["주차관리과", "교통행정과", "건설과", "도시정비과", "건축과", "자원순환과", "환경위생과", "산림녹지과", "경제진흥과", "일자리정책과", "해양수산과", "안전총괄과", "도시재생과", "문화예술과", "관광홍보과", "복지정책과", "노인장애인복지과", "시설관리사업소", "체육홍보과", "보건행정과", "건강증진과", "기획혁신과"]

[page]
new_ui = true #구형 UI ON/OFF (최초 메인 화면만 해당)
settingpage = true #설정 페이지 온오프
staticpage = true #통계페이지 온오프
filepage = true #파일 입력 온오프
manualpage = true #직접 입력 온오프
feedback = false #피드백 페이지 온오프


[sub]
accept  = "조속히 처리하겠습니다."
particle_accept = "현장확인 후 조속히 처리하겠음."
unaccept = "검토 이후 요청을 이행하기 어려움."

[format]
format = "1. 귀하의 가정에 행복이 가득하시길 바랍니다.\n\n2. 귀하의 민원내용은 [민원요지]에 관한 것으로 이해(또는 판단) 됩니다.\n\n3. 귀하의 질의사항에 대해 검토한 의견은 다음과 같습니다.\n\n가. [답변내용]\n\n4. 귀하의 질문에 만족스러운 답변이 되었기를 바라며, 답변 내용에 대한 추가 설명이 필요한 경우에는 사하구 [부서명]([이름], ☎[전화번호])에게 연락주시면 친절히 안내해 드리도록 하겠습니다.\n감사합니다.끝."
